"""using owner profile id in property

Revision ID: 11804d708e18
Revises: 3becb2b9ac29
Create Date: 2026-02-27 19:20:59.695008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11804d708e18'
down_revision: Union[str, Sequence[str], None] = '3becb2b9ac29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('owner_profile_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.create_index(op.f('ix_properties_owner_profile_id'), 'properties', ['owner_profile_id'], unique=False)
    op.drop_constraint(op.f('properties_owner_id_fkey'), 'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'owner_profiles', ['owner_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('properties', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_foreign_key(op.f('properties_owner_id_fkey'), 'properties', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_properties_owner_profile_id'), table_name='properties')
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.drop_column('properties', 'owner_profile_id')
    # ### end Alembic commands ###
